spring:
  application:
    name: LoggingOperations
  datasource:
    url: jdbc:postgresql://localhost:5433/devdb
    username: devuser
    password: devpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
